<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{{ base_url() }}/assets/images/icon.png">

    <title>FS | Portal de Operações</title>

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:400,300,500,700">
    <link rel="stylesheet" type="text/css" href="{{ base_url() }}/web/style.min.css">
</head>

<body class="gray-bg">
    <div class="middle-box text-center animated fadeInDown">
        <h1>404</h1>
        <h3 class="font-bold">Pagina não Encontrada</h3>

        <div class="error-desc">
            Desculpe, mas a página que você está procurando não foi encontrada. Verifique a URL ou tente se logar novamente clicando no botão abaixo.
            <br/><a onclick="history.back()" class="btn btn-primary m-t">Voltar</a>
        </div>
    </div>
</body>
</html>