{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('inserir-fraseologia') }}">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Tipo</label>
                                <div class="col-sm-4">
                                    <select class="form-control select2" name="type" id="type">
                                        <option value="">[Selecione um tipo]</option>
                                        {% for tipo in tipos %}
                                        <option value="{{ tipo.type }}" title="{{ tipo.description }}">{{ tipo.brief_description }}</option>
                                        {% endfor %}
                                    </select> 
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Produto</label>
                                <div class="col-sm-4">
                                    <select class="form-control select2" name="product" id="product">
                                        <option value="">[Selecione um produto]</option>
                                        {% for produto in produtos %}
                                        <option value="{{ produto.id }}">{{ produto.name }}</option>
                                        {% endfor %}
                                    </select> 
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Campanha</label>
                                <div class="col-sm-4">
                                    <select class="form-control select2" name="campaignName" id="campaignName">
                                        <option value="">[Selecione uma campanha]</option>
                                        {% for campanha in campanhas %}
                                        <option value="{{ campanha.id }}">{{ campanha.name }}</option>
                                        {% endfor %}
                                    </select> 
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Operadora</label>
                                <div class="col-sm-4">
                                <select  class="form-control select2" name="carrier" id="carrier">
                                    <option value="">[Selecione uma operadora]</option>
                                    {% for operadora in operadoras %}
                                    <option value="{{ operadora }}">{{ operadora }}</option>
                                    {% endfor %}
                                </select>   
                                </div>
                            </div>  

                            <div class="form-group">
                                <label class="col-sm-2 control-label">LA</label>
                                <div class="col-sm-4">
                                <select class="form-control select2" name="shortNumber" id="shortNumber">
                                    <option value="">[Selecione um la]</option>
                                    {% for shortnumber in la %}
                                    <option value="{{ shortnumber }}">{{ shortnumber }}</option>
                                    {% endfor %}
                                </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Mensagem</label>
                                    <div class="col-sm-4">

<!-- <textarea id="message"></textarea>
<textarea id="valeu" name="valeu"></textarea>
<div id="teste"></div>
<small class="caracteres"></small>
 -->

                                    <textarea class="form-control" rows="6" name="messages" id="msg" required="true"></textarea>
                                    <button type="button" class="btn btn-block btn-outline btn-primary"><i class="fa fa-plus"></i> Adicionar</button>
                                    <small class="caracteres"></small>

                                </div>

                                    <div class="col-sm-4">

<div class="panel panel-primary">
                                        <div class="panel-heading">
                                            Pre-visualização da Mensagem
                                        </div>
                                        <div class="panel-body">
                                            
                                        </div>
                                    </div>
                                    </div>

                           </div> 

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Ordene as fraseologias</label>
                                <div class="col-sm-4">
 
                                </div>
                            </div>  

                                   
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}