{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">               
                        {% for perms in sessao.permissions %}
                            {% if perms.name == permissoes.inserir %}
                                <a class="btn btn-success" type="button" href="{{ path_for('inserir-fraseologia') }}"><i class="fa fa-plus"></i> Adicionar Fraseologia</a>
                            {% endif %}
                        {% endfor %}

                        {% for perms in sessao.permissions %}
                            {% if perms.name == permissoes.publicar %}
                                <button class="btn btn-info poupup"><i class="fa fa-undo"></i> Publicar Fraseologias</button>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="ibox-content">
                        {% for item in messages.success %}
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            {{item}}
                        </div>
                        {% endfor %}

                        <div class="table-responsive" style="overflow: hidden;">
                            <form id="filterRows">
                                <table id="{{ pagina }}" class="table table-striped table-bordered table-hover">
                                    <thead>                                  
                                        <tr>
                                            <th style="width: 15px;"></th> 
                                            <th style="width: 20%;">
                                                <select class="form-control select2 form-search" name="campaignUuid" id="campaignUuid">
                                                    <option value="">[FILTRAR PELA CAMPANHA]</option>
                                                    {% for campanha in campanhas %}
                                                        <option value="{{ campanha.id }}">{{ campanha.name }}</option>
                                                    {% endfor %}
                                                </select>                                         
                                            </th>
                                            <th style="width: 15%;">
                                                <select class="form-control select2 form-search" name="productId" id="productId">
                                                    <option value="">[FILTRAR POR PRODUTO]</option>
                                                    {% for produto in produtos %}
                                                        <option value="{{ produto.id }}">{{ produto.name }}</option>
                                                    {% endfor %}
                                                </select>                                            
                                            </th>
                                            <th style="width: 10%;">
                                                <select class="form-control select2 form-search" name="shortNumber" id="shortNumber">
                                                    <option value="">[FILTRAR POR LA]</option>
                                                    {% for shortnumber in la %}
                                                        <option value="{{ shortnumber }}">{{ shortnumber }}</option>
                                                    {% endfor %}
                                                </select>
                                            </th>
                                            <th style="width: 30%;">
                                                <select class="form-control select2 form-search" name="type" id="type">
                                                    <option value="">[FILTRAR POR TIPO]</option>
                                                    {% for tipo in tipos %}
                                                        <option value="{{ tipo.type }}" title="{{ tipo.description }}">{{ tipo.brief_description }}</option>
                                                    {% endfor %}
                                                </select>                                            
                                            </th>
                                            <th style="width: 30%;">
                                                <select  class="form-control select2 form-search" name="carrier" id="carrier">
                                                    <option value="">[FILTRAR POR OPERADORA]</option>
                                                    {% for operadora in operadoras %}
                                                        <option value="{{ operadora }}">{{ operadora }}</option>
                                                    {% endfor %}
                                                </select>                                            
                                            </th>
                                           <th style="width: 10px;"></th>                                  
                                        </tr>                                    
                                    </thead>                                
                                    <thead>
                                      <tr>
                                        <th style="width: 15px;">#</th>
                                        <th>CAMPANHA</th>
                                        <th>PRODUTO</th>
                                        <th style="width: 10%;">LA</th>
                                        <th>TIPO</th>
                                        <th style="width: 15%;">OPERADORA</th>                                                                        
                                        <th style="width: 10px;">AÇÕES</th>                                   
                                      </tr>
                                    </thead>
                                </table>
                            </form>
                        </div>                       
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}