{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    {% for perms in sessao.permissions %}
                        {% if perms.name == permissoes.inserir %}
                            <a class="btn btn-success" type="button" href="{{ path_for('inserir-parceiro') }}"><i class="fa fa-plus"></i> Adicionar Parceiro</a>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <div class="ibox-content">
                        {% for item in messages.success %}
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            {{item}}
                        </div>
                        {% endfor %}

                        <form role="form" class="form-inline" id="filterRows">
                            <div class="form-group">
                                Filtros: &nbsp; <select class="form-control form-search" name="type" id="type">
                                    <option value="">[Todos os tipos]</option>
                                    <option value="CONTENT">Conteúdo</option>
                                    <option value="MEDIA">Mídia</option>
                                    <option value="MEDIA_AND_CONTENT">Mídia/Conteúdo</option>
                                </select>
                            </div>
                        </form>
                        <hr>
                        <div class="table-responsive">
                            <table id="{{ pagina }}" class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                      <th style="width: 30px;">#</th>
                                      <th>NOME</th>
                                      <th>TIPO</th>
                                      <th style="width: 40px;">AÇÕES</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}