{% extends "layout/layout.phtml" %}

{% block content %}
            <div class="wrapper wrapper-content animated fadeInRight">
               <div class="row">
                  <div class="col-lg-12">
                     <div class="ibox">
                        <div class="ibox-title">
                           <h5>Campanhas</h5>
                        </div>
                        <div class="ibox-content">
                           <form id="form" action="#" class="wizard-big">
                              <h1>CRIAR CAMPANHA</h1>
                              <fieldset>
                                 <h2>Nova Campanha</h2>
                                 <div class="row">
                                    <div class="col-lg-6">
                                       <div class="form-group">
                                          <label>Nome da Campanha *</label>
                                          <input id="name" name="name" type="text" class="form-control required">
                                       </div>
                                       <div class="form-group">
                                          <label>Ação *</label>
                                          <input id="surname" name="surname" type="text" class="form-control required">
                                       </div>
                                    </div>
                                    <div class="col-lg-6">
                                       <div class="form-group">
                                          <label>LA *</label>
                                          <input id="email" name="email" type="text" class="form-control required">
                                       </div>
                                       <div class="form-group">
                                          <label>Operadora *</label>
                                          <input id="address" name="address" type="text" class="form-control">
                                       </div>
                                    </div>
                                 </div>
                              </fieldset>
                              <h1>CRIAR FRASEOLOGIAS</h1>
                              <fieldset>
                                 <h2>Novas Fraseologias</h2>
                                 <div class="row">
                                    <div class="col-lg-6">
                                       <div class="form-group">
                                          <label>Tipo *</label>
                                          <input id="name" name="name" type="text" class="form-control required">
                                       </div>
                                       <div class="form-group">
                                          <label>Produto *</label>
                                          <input id="surname" name="surname" type="text" class="form-control required">
                                       </div>
                                    </div>
                                    <div class="col-lg-6">
                                       <div class="form-group">
                                          <label>Operadora *</label>
                                          <input id="email" name="email" type="text" class="form-control required">
                                       </div>
                                       <div class="form-group">
                                          <label>LA *</label>
                                          <input id="address" name="address" type="text" class="form-control">
                                       </div>
                                    </div>
                                 </div>
                              </fieldset>
                              <h1>TESTAR FRASEOLOGIAS</h1>
                              <fieldset>
                                 <div class="text-center" style="margin-top: 120px">
                                    <h2>Efetuar o teste das fraseologias cadastradas via SMS!</h2>
                                 </div>
                              </fieldset>
                              <h1>FINALIZAR</h1>
                              <fieldset>
                                 <div class="text-center" style="margin-top: 120px">
                                    <h2>Mostra todo o conteúdo para o usuário confirmar e envia para o Backend!</h2>
                                 </div>                                 
                              </fieldset>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
{% endblock %}