{% include('layout/header.phtml') %}

<body class="gray-bg">
    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>
                <img src="{{ base_url() }}/assets/images/logo.png" style="width: 90px; margin-bottom: 20px;">
            </div>
            <form class="m-t" role="form">
                <div class="form-group">
                    <input type="text" id="username" class="form-control" placeholder="Usuário" required="true">
                </div>
                <div class="form-group">
                    <input type="password" id="password" class="form-control" placeholder="Senha" required="true">
                </div>
                <button class="ladda-button btn btn-primary full-width m-b" type="button" id="login" data-style="expand-right" style="background-color: #2DBCB5;"><span class="ladda-label">Entrar</span><span class="ladda-spinner"></span><div class="ladda-progress" style="width: 0px;"></div></button>
                <div class="alert alert-danger alert-dismissable" style="display: none;"></div>
            </form>
            <p class="m-t"> <small>FS © 2018</small> </p>
        </div>
    </div>
</body>

{% include('layout/footer.phtml') %}