{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('editar-perfil', {id: id}) }}">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Nome</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="name" required="true" value="{{ rows.name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Descrição</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="description" required="true" value="{{ rows.description }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Permissões</label>
                                    <div class="col-sm-10">
                                        <div class="tabs-container">
                                            <ul class="nav nav-tabs">
                                                {% for sistema, permissao in permissoes %}
                                                    <li {% if sistema == 'configuracoes' %} class="active" {% endif %}><a data-toggle="tab" href="#tab-{{sistema}}"> <i class="fa fa-laptop"></i>{{ sistema }}</a></li>
                                                {% endfor %}
                                            </ul>
                                            <div class="tab-content">
                                            {% for sistema, permissao in permissoes %}
                                                <div id="tab-{{sistema}}" class="tab-pane {% if sistema == 'configuracoes' %} active{% endif %}">
                                                    <div class="panel-body">
                                                        {% for perms, listagem in permissao %}
                                                        <div class="form-group">
                                                            <label class="col-sm-2 control-label">{{ perms | upper}}</label>
                                                            <div class="col-sm-10">
                                                                {% for lista in listagem  %}
                                                                    <div>
                                                                        <label>
                                                                            <input type="checkbox" name="permissions[]" value="{{lista.id}}" {% for gp_permissao in gp_permissoes %} {% if gp_permissao.id == lista.id %} checked="true" {% endif %}{% endfor %}> {{lista.name}}
                                                                        </label>
                                                                    </div>
                                                                {% endfor %}
                                                            </div>
                                                        </div>
                                                        <div class="hr-line-dashed"></div>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                            </div>                          
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}