{% extends "layout/layout.phtml" %}

{% block content %}

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Detalhe do Produto</h5>
                    </div>
                    <div class="ibox-content">
                        <blockquote>
                            <p>{{ produto.name }}</p>
                            <small><strong>Parceiro:</strong> {{ produto.partners_name }}</small>
                            <small><strong>Tipo:</strong> {{ produto.type }}</small>
                            <small><strong>Status:</strong> {{ produto.active }}</small>
                            <small><strong>Canais:</strong> {{ produto.channels_name }}</small>
                            <small><strong>Operadoras:</strong> {{ produto.carriers }}</small>
                        </blockquote>
                        <h3>Fraseologias: </h3>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Operadora</th>
                                    <th>Tipo</th>
                                    <th>Mensagem</th>
                                    <th>Criado em</th>
                                    <th>Atualizado em</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for fraseologies in produto.fraseologies %}
                            <tr>
                                <td>{{ fraseologies.id }}</td>
                                <td>{{ fraseologies.carrier }}</td>
                                <td>{{ fraseologies.type.type }}</td>
                                <td><textarea class="form-control" style="color: #31708f; background-color: #d9edf7; border-color: #bce8f1;" disabled>{{ fraseologies.message }}</textarea></td>
                                <td>{{ fraseologies.createdAt }}</td>
                                <td>{{ fraseologies.updatedAt }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>

                            {% if produto.fraseologies == false %}
                            <tbody>
                                <tr>
                                    <td colspan="6" align="center">Nenhum registro encontrado</td>
                                </tr>
                            </tbody>
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}