{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('editar-permissao', {id: id}) }}">
                            
                           <div class="form-group">
                                <label class="col-sm-2 control-label">Interface *:</label>
                                <div class="col-sm-4">
                                    <select class="form-control" name="system" required="true">
                                        <option selected=true value="">Selecione uma opção...</option>
                                        {% for k, v in sistemas %}
                                        <option value="{{k}}" {% if rows.system == k %} selected="true" {% endif %} >{{v}}</option>
                                        {% endfor %}                                          
                                    </select>
                                </div>
                            </div>  

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Página *:</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control valida-permissao" name="uri" required="true" value="{{ rows.uri }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Nome *:</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control valida-permissao" name="name" required="true" value="{{ rows.name }}">
                                </div>
                            </div>
                            
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}