{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">                    
                    {% for perms in sessao.permissions %}
                        {% if perms.name == permissoes.inserir %}
                            <a class="btn btn-success" type="button" href="{{ path_for('inserir-permissao') }}" ><i class="fa fa-plus"></i> Adicionar Permissão</a>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <div class="ibox-content">
                        {% for item in messages.success %}
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            {{item}}
                        </div>
                        {% endfor %}
                        <div class="table-responsive">
                            <table id="{{ pagina }}" class="table table-striped table-bordered table-hover">
                                <thead>
                                  <tr>
                                    <th style="width: 50px;">#</th>
                                    <th>Nome</th>
                                    <th>Interface</th>
                                    <th>Página</th>                                                                      
                                    <th style="width: 50px;">Ações</th>                                    
                                  </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}