{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('editar-parceiro', {id: id}) }}">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Nome *:</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="name" required="true" value="{{ rows.name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Tipo *:</label>
                                <div class="col-sm-4">
                                <select class="form-control" name="type" id="type" required="true">
                                    <option selected="true" value="">Selecione um tipo...</option>
                                        <option value="MEDIA" {% if rows.type == 'MEDIA'%} selected="true" {% endif %}>Mídia</option>
                                        <option value="CONTENT" {% if rows.type == 'CONTENT'%} selected="true" {% endif %}>Conteúdo</option>
                                        <option value="MEDIA_AND_CONTENT" {% if rows.type == 'MEDIA_AND_CONTENT'%} selected="true" {% endif %}>Mídia/Conteúdo</option>
                                    </select>
                                </div>
                            </div>                             
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}