{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                        {% for perms in sessao.permissions %}
                            {% if perms.name == permissoes.inserir %}
                                <a class="btn btn-success" type="button" href="{{ path_for('inserir-noticia') }}"><i class="fa fa-plus"></i> Adicionar Notícia</a>
                            {% endif %}
                        {% endfor %}

                        {% for perms in sessao.permissions %}
                            {% if perms.name == permissoes.importar %}
                                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal"><i class="fa fa-upload"> </i> Importar Arquivos</button>
                            {% endif %}
                        {% endfor %}                        

                        </div>
                        <div class="ibox-content">
                            {% for item in messages.success %}
                            <div class="alert alert-success alert-dismissable">
                                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                {{item}}
                            </div>
                            {% endfor %}
                            <div class="table-responsive" style="overflow: hidden;">
                                <form id="filterRows">
                                    <table id="{{ pagina }}" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th style="width: 3%"></th> 
                                                <th style="width: 13%;">
                                                    <select class="form-control select2 offerId" name="offerId">
                                                        <option value="">[FILTRAR PELA OFERTA]</option>
                                                        {% for oferta in ofertas %}
                                                            <option value="{{ oferta.id }}">{{ oferta.name }}</option>
                                                        {% endfor %}
                                                    </select>
                                                </th>
                                                <th style="width: 15%;">
                                                  <select class="form-control form-search channelId" name="channelId" style="height: 29px; padding: 5px; font-size: 13px; color: #000; width: 210px;">
                                                    <option value="">[FILTRAR PELO CANAL]</option>
                                                  </select>
                                                </th>
                                                <th style="width: 25%;"></th>
                                                <th style="width: 15%;">
                                                    <select class="form-control select2 form-search" name="status" id="status">
                                                        <option value="">[FILTRAR PELO STATUS]</option>
                                                        <option value="PROCESSING">Processando</option>
                                                        <option value="SCHEDULED">Agendado</option>
                                                        <option value="SENT">Enviado</option>
                                                        <option value="WAITING_APPROVAL">Aguardando Aprovação</option>
                                                    </select>
                                                </th>
                                                <th></th>
                                                <th></th>
                                                <th></th>
                                               <th style="width: 3%;"></th>                                  
                                            </tr>                                    
                                        </thead>
                                        <thead>
                                          <tr>
                                            <th>#</th>
                                            <th>OFERTA</th>
                                            <th>CANAL</th>
                                            <th>MENSAGEM</th>
                                            <th>STATUS</th>
                                            <th>DISPARADO</th>
                                            <th>CRIADO EM</th>
                                            <th>ATUALIZADO EM</th>
                                            <th>AÇÕES</th>                                    
                                          </tr>
                                        </thead>
                                    </table>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
            <div class="modal-dialog">
                <div class="modal-content animated bounceInRight">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                        <i class="fa fa-upload modal-icon"></i>
                        <h4 class="modal-title">Importar Notícias</h4>
                    </div>
                    <div class="modal-body">
                        <p>Para fazer o download do template do arquivo, <strong><a href="{{ base_url() }}/assets/modelo.xls">clique aqui.</a></strong></p>
                        <form action="{{ path_for('importar-noticia') }}" enctype="multipart/form-data" method="POST">
                            <div class="form-group">
                                <label>Oferta *:</label> 
                                <select class="form-control" name="offer" id="offerByChannels" required="true">
                                    <option value="">[Selecione uma oferta]</option>                                    
                                    {% for oferta in ofertas %}
                                        <option value="{{ oferta.id }}">{{ oferta.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Canal *:</label> 
                                <select class="form-control" name="channel" id="channelsByOffers" required="true">
                                    <option value="">[Todos os canais]</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Selecione o arquivo: *:</label> 
                                <input class="form-control m-b" type="file" name="file" id="file" accept="application/vnd.ms-excel" required="true">
                            </div>      
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-white" type="button" class="close" data-dismiss="modal">Cancelar</button>
                        <button class="btn btn-primary" type="submit">Salvar</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>  

{% endblock %}