{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <a class="btn btn-success" type="button" href="{{ base_url() }}/configuracoes/empresas/inserir" ><i class="fa fa-plus"></i> Adicionar Empresas</a>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table id="{{endpoint}}" class="table table-striped table-bordered table-hover">
                                <thead>
                                  <tr>
                                    <th>#</th>
                                    <th>Nome</th>
                                    <th>Ações</th>                                    
                                  </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}