{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('editar-luckynumber', {id: id}) }}">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="message">Tipo *:</label>
                                <div class="col-sm-4">
                                    <select class="form-control select2" name="type" id="type" required="true">
                                        <option selected="true" value="">[Selecione um tipo]</option>
                                        {% for tipo in tipos %}
                                            <option value="{{ tipo.name }}" {% if rows.type == tipo.name %} selected="true" {% endif %}>{{ tipo.name }}</option>
                                        {% endfor %}                                          
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="message">Cenário *:</label>
                                <div class="col-sm-4">
                                    <select class="form-control select2" name="scenario" id="scenario" required="true">
                                        <option selected="true" value="">[Selecione um cenário]</option>
                                        {% for cenario in cenarios %}
                                            <option value="{{ cenario.name }}" {% if rows.scenario == cenario.name %} selected="true" {% endif %}>{{ cenario.name }}</option>
                                        {% endfor %}                                         
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="message">Quantidade de números *:</label>
                                <div class="col-sm-4">
                                    <input class="form-control" type="quantity" name="quantity" onkeyup="somenteNumeros(this);" required="true" value="{{ rows.quantity }}">
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}