{% for perms in sessao.permissions %}
    {% if perms.name == permissoes.interface %}

        <li {{(menu_sistema == 'campanhas') ? 'class=active style=background-color:#fff;' : ''}}>
            <a href="#" {{(menu_sistema == 'campanhas') ? 'class=active style=background-color:#2DBCB5;color:#fff;' : ''}}>
                <i class="fa fa-newspaper-o"></i>
                <span class="nav-label">Campanhas</span><span class="fa arrow"></span>
            </a>
            <ul class="nav nav-second-level collapse">
                <li {{ menu_consumers }}>
                    <a href="{{ path_for('listar-consumer') }}">
                        <i class="fa fa-bullseye"></i>
                        <span class="nav-label">Consumers</span>
                    </a>
                </li>
                <li {{ menu_acoes }}>
                    <a href="{{ path_for('listar-acao') }}">
                        <i class="fa fa-send"></i>
                        <span class="nav-label">Ações</span>
                    </a>
                </li>                                 
            </ul>
        </li>

    {% endif %}
{% endfor %}