{% for perms in sessao.permissions %}
    {% if perms.name == permissoes.interface %}

        <li {{(menu_sistema == 'configuracoes') ? 'class=active style=background-color:#fff;' : ''}}>
            <a href="#" {{(menu_sistema == 'configuracoes') ? 'class=active style=background-color:#2DBCB5;color:#fff;' : ''}}>
                <i class="fa fa-cog"></i>
                <span class="nav-label">Configurações</span><span class="fa arrow"></span>
            </a>
            <ul class="nav nav-second-level collapse">
                <li {{ menu_empresas }}>
                    <a href="{{ path_for('listar-empresa') }}">
                        <i class="fa fa-home"></i>
                        <span class="nav-label">Empresas</span>
                    </a>
                </li>
                <li {{ menu_usuarios }}>
                    <a href="{{ path_for('listar-usuario') }}">
                        <i class="fa fa-users"></i>
                        <span class="nav-label">Usuários</span>
                    </a>
                </li>
                <li {{ menu_permissoes }}>
                    <a href="{{ path_for('listar-permissao') }}">
                        <i class="fa fa-lock"></i>
                        <span class="nav-label">Permissões</span>
                    </a>
                </li>
                <li {{ menu_perfil }}>
                    <a href="{{ path_for('listar-perfil') }}">
                        <i class="fa fa-briefcase"></i>
                        <span class="nav-label">Perfis</span>
                    </a>
                </li>                    
            </ul>
        </li>

    {% endif %}
{% endfor %}