            <li {% if menu_sistema == 'interatividade' %} class="active" style="background-color:#ffffff;" {% endif %}>
                <a href="#" {% if menu_sistema == 'interatividade' %} class="active" style="background-color:#2DBCB5; color:#FFFFFF;" {% endif %}><i class="fa fa-cog"></i><span class="nav-label">Interatividade</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li {% if pagina == 'parceiros' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/interatividade/parceiros/listar"><i class="fa fa-flag"></i><span class="nav-label">Parceiros</span></a>
                    </li>
                    <li {% if pagina == 'ofertas' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/interatividade/ofertas/listar"><i class="fa fa-certificate"></i><span class="nav-label">Ofertas</span></a>
                    </li>
                    <li {% if pagina == 'canais' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/interatividade/canais/listar"><i class="fa fa-tags"></i><span class="nav-label">Canais</span></a>
                    </li>
                    <li {% if pagina == 'noticias' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/interatividade/noticias/listar"><i class="fa fa-bullseye"></i><span class="nav-label">Notícias</span></a>
                    </li>                    
                    <li {% if pagina == 'produtos' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/interatividade/produtos/listar"><i class="fa fa-star"></i><span class="nav-label">Produtos</span></a>
                    </li>
                    <li {% if pagina == 'luckynumber' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/interatividade/luckynumber/listar"><i class="fa fa-retweet"></i><span class="nav-label">Luckynumber</span></a>
                    </li>
                    <li {% if pagina == 'fraseologias' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/interatividade/fraseologias/listar"><i class="fa fa-bullhorn"></i><span class="nav-label">Fraseologias</span></a>
                    </li>
                </ul>
            </li>