{% for perms in sessao.permissions %}
    {% if perms.name == permissoes.interface %}

        <li {{(menu_sistema == 'interatividade') ? 'class=active style=background-color:#fff;' : ''}}>
            <a href="#" {{(menu_sistema == 'interatividade') ? 'class=active style=background-color:#2DBCB5;color:#fff;' : ''}}>
                <i class="fa fa-sitemap"></i>
                <span class="nav-label">Interatividade</span><span class="fa arrow"></span>
            </a>
            <ul class="nav nav-second-level collapse">
                <li {{ menu_parceiros }}>
                    <a href="{{ path_for('listar-parceiro') }}">
                        <i class="fa fa-flag"></i>
                        <span class="nav-label">Parceiros</span>
                    </a>
                </li>
                <li {{ menu_ofertas }}>
                    <a href="{{ path_for('listar-oferta') }}">
                        <i class="fa fa-certificate"></i>
                        <span class="nav-label">Ofertas</span>
                    </a>
                </li>
                <li {{ menu_canais }}>
                    <a href="{{ path_for('listar-canal') }}">
                        <i class="fa fa-tags"></i>
                        <span class="nav-label">Canais</span>
                    </a>
                </li>
                <li {{ menu_noticias }}>
                    <a href="{{ path_for('listar-noticia') }}">
                        <i class="fa fa-bullseye"></i>
                        <span class="nav-label">Notícias</span>
                    </a>
                </li>                    
                <li {{ menu_produtos }}>
                    <a href="{{ path_for('listar-produto') }}">
                        <i class="fa fa-star"></i>
                        <span class="nav-label">Produtos</span>
                    </a>
                </li>
                <li {{ menu_luckynumber }}>
                    <a href="{{ path_for('listar-luckynumber') }}">
                        <i class="fa fa-retweet"></i>
                        <span class="nav-label">Luckynumber</span>
                    </a>
                </li>
                <li {{ menu_fraseologias }}>
                    <a href="{{ path_for('listar-fraseologia') }}">
                        <i class="fa fa-bullhorn"></i>
                        <span class="nav-label">Fraseologias</span>
                    </a>
                </li>
            </ul>
        </li>

    {% endif %}
{% endfor %}