{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('inserir-canal') }}">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="name">Canal</label>
                                <div class="col-md-4">
                                    <input class="form-control" type="text" id="name" name="name" placeholder="Digite um nome de canal" required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Oferta</label>
                                <div class="col-md-4">
                                    <select class="form-control select2" name="offer" id="offer" required="true">
                                        <option value="">[Selecione uma oferta]</option>
                                        {% for oferta in ofertas %}
                                            <option value="{{ oferta.id }}" data-partner-id="{{ oferta.partner_id }}" >{{ oferta.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Parceiro</label>
                                <div class="col-md-4">
                                    <select class="form-control" name="partner" id="partner">
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Etiqueta SMS</label>
                                <div class="col-md-4">
                                    <input class="form-control" type="text" id="smsLabel" name="smsLabel" placeholder="Digite um nome de etiqueta SMS" required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Etiqueta Web</label>
                                <div class="col-md-4">
                                    <input class="form-control" type="text" id="webLabel" name="webLabel" placeholder="Digite um nome de etiqueta Web" required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Qtde. de mensagem por dia</label>
                                <div class="col-md-4">
                                    <input class="form-control" type="text" id="messagesPerDay" name="messagesPerDay" value="" maxlength="50" onkeyup="somenteNumeros(this);" required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Ativo</label>
                                <div class="col-sm-10">
                                    <div><label> <input type="radio" name="active" value="1" checked="" required="true">Sim</label></div>
                                    <div><label> <input type="radio" name="active" value="0">Não</label></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Data de Envio</label>
                                <div class="col-sm-10">
                                    <div class="row">
                                        <div class="col-sm-2 control-label">
                                            <select id="weekday" class="form-control" required="true">
                                                <option value="">[Selecione uma opção...]</option>
                                                {% for key, value in datas %}
                                                <option value="{{ key }}">{{ value }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="col-sm-2 control-label">
                                            <input type="text" id="time" class="form-control" required="true">
                                        </div>
                                        <div class="col-md-1">
                                            <button type="button" id="add" class="btn btn-success btn-circle"><i class="fa fa-plus"></i></button>   
                                        </div>
                                    </div>

                                    <br>

                                    <div class="col-sm-12">
                                        <div class="row">
                                            <div class="table-responsive">
                                                <table class="table table-bordered">
                                                    <thead>
                                                        <tr>
                                                            <th>Domingo</th>
                                                            <th>Segunda</th>
                                                            <th>Terça</th>
                                                            <th>Quarta</th>
                                                            <th>Quinta</th>
                                                            <th>Sexta</th>
                                                            <th>Sabado</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                            <td id="td-sunday"></td>
                                                            <td id="td-monday"></td>
                                                            <td id="td-tuesday"></td>
                                                            <td id="td-wednesday"></td>
                                                            <td id="td-thursday"></td>
                                                            <td id="td-friday"></td>
                                                            <td id="td-saturday"></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>                        
                                    </div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}