{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    {% for perms in sessao.permissions %}
                        {% if perms.name == permissoes.inserir %}
                            <a class="btn btn-success" type="button" href="{{ path_for('inserir-canal') }}"><i class="fa fa-plus"></i> Adicionar Canal</a>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <div class="ibox-content">
                        {% for item in messages.success %}
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            {{item}}
                        </div>
                        {% endfor %}

                        <form role="form" class="form-inline" id="filterRows">
                            <div class="form-group">
                                <strong>Filtros:</strong> &nbsp;
                                <select class="form-control select2 form-search" name="name" id="name">
                                    <option value="">[FILTRAR PELO NOME]</option>
                                    {% for canal in canais %}
                                    <option value="{{ canal.name }}">{{ canal.name }}</option>
                                    {% endfor %}
                                </select>                               
                            </div>
                            <div class="form-group">
                                <select class="form-control select2 form-search" name="offerId" id="offerId">
                                    <option value="">[FILTRAR PELA OFERTA]</option>
                                    {% for oferta in ofertas %}
                                    <option value="{{ oferta.id }}">{{ oferta.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control select2 form-search" name="messagesPerDay" id="messagesPerDay">
                                    <option value="">[FILTRAR PELA QUANTIDADE]</option>
                                    {% for i in 0..100 %}
                                    <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </form>

                        <div class="hr-line-dashed"></div>

                        <div class="table-responsive">                        
                            <table id="{{ pagina }}" class="table table-striped table-bordered table-hover">
                                <thead>
                                  <tr>
                                    <th style="width: 50px;">#</th>
                                    <th>NOME</th>
                                    <th>OFERTA</th>
                                    <th>MENSAGENS POR DIA</th>
                                    <th>STATUS</th>                                                                        
                                    <th style="width: 50px;">AÇÕES</th>                                    
                                  </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}