{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('inserir-usuario') }}">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Nome *:</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="name" required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Empresa *:</label>
                                <div class="col-sm-4">
                                    <select class="form-control" name="workplace_id" id="workplace_id" required="true">
                                        <option selected=true value="">Selecione uma opção...</option>
                                        {% for empresa in empresas %}
                                        <option value="{{empresa.id}}">{{empresa.name}}</option>
                                        {% endfor %}                                         
                                    </select>
                                </div>
                            </div> 
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Perfil *:</label>
                                <div class="col-sm-4">
                                    <select class="form-control" name="usergroup_id" id="usergroup_id" required="true">
                                        <option selected=true value="">Selecione uma opção...</option>
                                        {% for perfils in perfil %}
                                        <option value="{{perfils.id}}">{{perfils.name}}</option>
                                        {% endfor %}   
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Usuário *:</label>
                                <div class="col-sm-4">
                                    <input class="form-control" type="text" id="username" name="username" maxlength="45" required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Senha *:</label>
                                <div class="col-sm-4">
                                    <input class="form-control" type="password" id="password" name="password" maxlength="135" required="true">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Alterar senha 1º acesso:</label>
                                <div class="col-sm-4">
                                    <select class="form-control" name="force_pass_change" id="force_pass_change" required="true">
                                        <option value="-1">Não</option>
                                        <option value="1">Sim</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Habilitado:</label>
                                <div class="col-sm-4">
                                    <select class="form-control" name="enabled" class="select" id="enabled" required="true">
                                        <option value="-1">Não</option>
                                        <option value="1">Sim</option>
                                    </select>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}