{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    {% for perms in sessao.permissions %}
                        {% if perms.name == permissoes.inserir %}
                            <a class="btn btn-success" type="button" href="{{ path_for('inserir-acao') }}"><i class="fa fa-plus"></i> Adicionar Ação</a>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <div class="ibox-content">
                        {% for item in messages.success %}
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            {{item}}
                        </div>
                        {% endfor %}
                        <div class="table-responsive" style="overflow: hidden;">
                            <form id="filterRows">                            
                                <table id="{{ pagina }}" class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th style="width: 3%"></th> 
                                            <th style="width: 30%;">
                                                <select class="form-control select2 form-search" name="name" id="name">
                                                    <option value="">[FILTRAR PELO NOME]</option>
                                                    {% for canal in canais %}
                                                        <option value="{{ canal.name }}">{{ canal.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            </th>
                                            <th style="width: 30%;">
                                                <select class="form-control select2 form-search" name="offerId" id="offerId">
                                                    <option value="">[FILTRAR PELA AÇÃO]</option>
                                                    {% for oferta in ofertas %}
                                                        <option value="{{ oferta.id }}">{{ oferta.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            </th>
                                           <th style="width: 3%;"></th>                                  
                                        </tr>                                    
                                    </thead>
                                    <thead>
                                      <tr>
                                        <th style="width: 50px;">#</th>
                                        <th>NOME</th>
                                        <th>AÇÃO</th>
                                        <th style="width: 50px;">AÇÕES</th>                                    
                                      </tr>
                                    </thead>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}