	<script type="text/javascript">

		var endpoint          = '{{ endpoint }}';
		var hostname          = '{{ hostname }}';
		var token             = '{{ token }}';
		var pagina            = '{{ pagina }}';
		
	</script>

	<!-- Scripts -->
	<script src="{{ base_url() }}/assets/js/plugins/jquery-2.1.1.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/bootstrap.min.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/jquery.metisMenu.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/jquery.slimscroll.min.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/inspinia.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/pace.min.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/jquery.steps.min.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/jquery.validate.min.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/jquery.wizard.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/datatables.min.js"></script>
	<script src="{{ base_url() }}/assets/js/plugins/sweetalert.min.js"></script>

	<!-- Functions -->
	<script src="{{ base_url() }}/assets/js/functions/datatables.js?v={{random()}}"></script>   
	<script src="{{ base_url() }}/assets/js/functions/alerts.js?v={{random()}}"></script>   
	<script src="{{ base_url() }}/assets/js/functions/validations.js?v={{random()}}"></script>

</body>
</html>