	<script type="text/javascript">
	
		var base_url		  = '{{ base_url() }}';
		var pagina            = '{{ pagina }}';
		var endpoint          = '{{ endpoint }}';
		var hostname          = '{{ hostname }}';
		var token             = '{{ token }}';
		
	</script>
	<script src="{{ base_url() }}/web/plugins.min.js"></script> 
	<script src="{{ base_url() }}/web/functions.min.js"></script>
</body>
</html>