<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>FS | Portal de Operações</title>
      <!-- Styles -->
      <link href="{{ base_url() }}/assets/css/bootstrap.min.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/font-awesome.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/custom.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/jquery.steps.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/animate.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/style.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/datatables.min.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/sweetalert.css" rel="stylesheet">
   </head>