<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>FS | Portal de Operações</title>
      <!-- Styles -->
      <link href="{{ base_url() }}/assets/css/bootstrap.min.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/font-awesome.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/custom.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/jquery.steps.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/animate.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/style.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/datatables.min.css" rel="stylesheet">
   </head>
   <body>
      <div id="wrapper">
        {% include 'layout/menu-left.phtml' %}
           <div id="page-wrapper" class="gray-bg">
            
            {% include 'layout/menu-top.phtml' %}
            
            {% block content %}{% endblock %}

            <div class="footer">
               <div class="pull-right">
                  <strong>Copyright FS</strong>© 2018
               </div>
            </div>
         </div>
      </div>

      <script type="text/javascript">
        
        var page = '{{ page }}';
        var gdu_hostname = '{{ gdu_hostname }}';
        var gdu_token = '{{ gdu_token }}';

      </script>

      <!-- Scripts -->
      <script src="{{ base_url() }}/assets/js/jquery-2.1.1.js"></script>
      <script src="{{ base_url() }}/assets/js/bootstrap.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.metisMenu.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.slimscroll.min.js"></script>
      <script src="{{ base_url() }}/assets/js/inspinia.js"></script>
      <script src="{{ base_url() }}/assets/js/pace.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.steps.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.validate.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.wizard.js"></script>
      <script src="{{ base_url() }}/assets/js/datatables.min.js"></script>

      <!-- Functions -->
      <script src="{{ base_url() }}/assets/functions/datatables.js"></script>      

   </body>
</html>