<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>FS | Portal de Operações</title>
      <!-- Styles -->
      <link href="{{ base_url() }}/assets/css/bootstrap.min.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/font-awesome.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/custom.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/jquery.steps.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/animate.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/style.css" rel="stylesheet">
      <link href="{{ base_url() }}/assets/css/datatables.min.css" rel="stylesheet">
   </head>
   <body>
      <div id="wrapper">
         <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
               <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header" align="center">
                        <div class="dropdown profile-element">
                            <span>
                                <img src="{{ base_url() }}/assets/images/logo.png" height="110px"/>
                            </span>
                        </div>
                        <div class="logo-element" style="background: #f3f3f4;">
                            <img src="{{ base_url() }}/assets/images/logo-2.png" />
                        </div>
                    </li>
                    <li>
                        <a href="{{ base_url() }}/"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span></a>
                    </li>
                    <!-- Menu Configurações do Sistema -->
                    <li>
                        <a href="#"><i class="fa fa-cog"></i><span class="nav-label">Configurações </span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse" style="height: 0px;">
                            <li>
                                <a href="{{ base_url() }}/configuracoes/empresas/listar"><i class="fa fa-home"></i><span class="nav-label">Empresas</span></a>
                            </li>
                            <li>
                            <a href="{{ base_url() }}/configuracoes/usuarios/listar"><i class="fa fa-users"></i><span class="nav-label">Usuários</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/configuracoes/perfis/listar"><i class="fa fa-briefcase"></i> <span class="nav-label">Perfis</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/configuracoes/permissoes/listar"><i class="fa fa-lock"></i> <span class="nav-label">Permissões</span></a>
                            </li>
                        </ul>
                    </li>
                    <!-- Menu Interatividade -->
                    <li>
                        <a href="#"><i class="fa fa-sitemap"></i><span class="nav-label">Interatividade</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                                <a href="#"><i class="fa fa-cogs"></i>Configurações <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level collapse" style="height: 0px;">
                                    <li>
                                        <a href="{{ base_url() }}/interatividade/configuracoes/parceiros/listar"><i class="fa fa-flag"></i><span class="nav-label">Parceiros</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/interatividade/configuracoes/ofertas/listar"><i class="fa fa-certificate"></i><span class="nav-label">Ofertas</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/interatividade/configuracoes/canais/listar"><i class="fa fa-tags"></i><span class="nav-label">Canais</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/interatividade/configuracoes/produtos/listar"><i class="fa fa-star"></i><span class="nav-label">Produtos</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/interatividade/configuracoes/luckynumber/listar"><i class="fa fa-retweet"></i><span class="nav-label">Luckynumber</span></a>
                                    </li>
                                </ul>
                                <li>
                                    <a href="{{ base_url() }}/interatividade/noticias/listar"><i class="fa fa-bullseye"></i><span class="nav-label">Notícias</span></a>
                                </li>
                                <li>
                                    <a href="{{ base_url() }}/interatividade/fraseologias/listar"><i class="fa fa-bullhorn"></i><span class="nav-label">Fraseologias</span></a>
                                </li>                                
                            </li>
                        </ul>
                    </li>
                    <!-- Menu Campanhas -->
                    <li>
                        <a href="#"><i class="fa fa-newspaper-o"></i><span class="nav-label">Campanhas</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                                <a href="#"><i class="fa fa-cogs"></i>Configurações <span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level collapse" style="height: 0px;">
                                    <li>
                                        <a href="{{ base_url() }}/campanhas/configuracoes/consumers/listar"><i class="fa fa-bullseye"></i><span class="nav-label">Consumers</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/campanhas/configuracoes/acoes/listar"><i class="fa fa-send"></i><span class="nav-label">Ações</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/campanhas/configuracoes/canais/listar"><i class="fa fa-list-ol"></i><span class="nav-label">Canais</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/campanhas/configuracoes/operadoras/listar"><i class="fa fa-phone"></i><span class="nav-label">Operadoras</span></a>
                                    </li>
                                    <li>
                                        <a href="{{ base_url() }}/campanhas/configuracoes/la/listar"><i class="fa fa-sort-numeric-asc"></i><span class="nav-label">LA</span></a>
                                    </li>
                                </ul>
                                <li><a href="{{ base_url() }}/campanhas/listar"><i class="fa fa-plus"></i>Listar Campanhas</a></li>
                            </li>
                        </ul>
                    </li>
               </ul>
            </div>
         </nav>
         <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm welcome-message" style="color:#fff;">Você está logado(a) como: <b>Admin</b></span>
                        </li>
                        <li>
                            <a href="" style="color:#fff;">
                                <i class="fa fa-pencil"></i> Alterar Senha
                            </a>
                        </li>
                        <li>
                            <a href="{{ base_url() }}/auth/logout" style="color:#fff;">
                                <i class="fa fa-sign-out"></i> Sair
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="row wrapper border-bottom white-bg page-heading">
               <div class="col-lg-10">
                  <h2>Bem-vindo ao Portal de Operações | FS</h2>
                  <ol class="breadcrumb">
                     <li>
                        <a>Home</a>
                     </li>
                     <li>
                        <a href="{{ base_url() }}/">Dashboard</a>
                     </li>
                  </ol>
               </div>
               <div class="col-lg-2">
               </div>
            </div>
            {% block content %}{% endblock %}
            <div class="footer">
               <div class="pull-right">
                  <strong>Copyright FS</strong>© 2018
               </div>
            </div>
         </div>
      </div>
      <!-- Scripts -->
      <script src="{{ base_url() }}/assets/js/jquery-2.1.1.js"></script>
      <script src="{{ base_url() }}/assets/js/bootstrap.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.metisMenu.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.slimscroll.min.js"></script>
      <script src="{{ base_url() }}/assets/js/inspinia.js"></script>
      <script src="{{ base_url() }}/assets/js/pace.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.steps.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.validate.min.js"></script>
      <script src="{{ base_url() }}/assets/js/jquery.wizard.js"></script>
      <script src="{{ base_url() }}/assets/js/datatables.min.js"></script>

    <script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 10,
                responsive: true,
                language: {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar: ",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                },            
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });

    </script>
   </body>
</html>