<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header" align="center">
                <div class="dropdown profile-element">
                    <span>
                        <img src="{{ base_url() }}/assets/images/logo.png" height="110px"/>
                    </span>
                </div>
                <div class="logo-element" style="background: #f3f3f4;">
                    <img src="{{ base_url() }}/assets/images/logo-2.png" />
                </div>
            </li>
            <li {% if menu_sistema == 'dashboard' %}class="active"{% endif %}>
                <a href="{{ base_url() }}/dashboard"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span></a>
            </li>
            <!-- Menu Configurações do Sistema -->
            <li {% if menu_sistema == 'configuracoes' %}class="active"{% endif %}>
                <a href="#"><i class="fa fa-cog"></i><span class="nav-label">Configurações </span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse" style="height: 0px;">
                    <li {% if pagina == 'empresas' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/configuracoes/empresas/listar"><i class="fa fa-home"></i><span class="nav-label">Empresas</span></a>
                    </li>
                    <li {% if pagina == 'usuarios' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/configuracoes/usuarios/listar"><i class="fa fa-users"></i><span class="nav-label">Usuários</span></a>
                    </li>
                    <li {% if pagina == 'perfil' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/configuracoes/perfil/listar"><i class="fa fa-briefcase"></i> <span class="nav-label">Perfis</span></a>
                    </li>
                    <li {% if pagina == 'permissoes' %}class="active"{% endif %}>
                        <a href="{{ base_url() }}/configuracoes/permissoes/listar"><i class="fa fa-lock"></i> <span class="nav-label">Permissões</span></a>
                    </li>
                </ul>
            </li>
            <!-- Menu Interatividade -->
            <li>
                <a href="#"><i class="fa fa-sitemap"></i><span class="nav-label">Interatividade</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li>
                        <a href="#"><i class="fa fa-cogs"></i>Configurações <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level collapse" style="height: 0px;">
                            <li>
                                <a href="{{ base_url() }}/interatividade/configuracoes/parceiros/listar"><i class="fa fa-flag"></i><span class="nav-label">Parceiros</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/interatividade/configuracoes/ofertas/listar"><i class="fa fa-certificate"></i><span class="nav-label">Ofertas</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/interatividade/configuracoes/canais/listar"><i class="fa fa-tags"></i><span class="nav-label">Canais</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/interatividade/configuracoes/produtos/listar"><i class="fa fa-star"></i><span class="nav-label">Produtos</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/interatividade/configuracoes/luckynumber/listar"><i class="fa fa-retweet"></i><span class="nav-label">Luckynumber</span></a>
                            </li>
                        </ul>
                        <li>
                            <a href="{{ base_url() }}/interatividade/noticias/listar"><i class="fa fa-bullseye"></i><span class="nav-label">Notícias</span></a>
                        </li>
                        <li>
                            <a href="{{ base_url() }}/interatividade/fraseologias/listar"><i class="fa fa-bullhorn"></i><span class="nav-label">Fraseologias</span></a>
                        </li>                                
                    </li>
                </ul>
            </li>
            <!-- Menu Campanhas -->
            <li>
                <a href="#"><i class="fa fa-newspaper-o"></i><span class="nav-label">Campanhas</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li>
                        <a href="#"><i class="fa fa-cogs"></i>Configurações <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level collapse" style="height: 0px;">
                            <li>
                                <a href="{{ base_url() }}/campanhas/configuracoes/consumers/listar"><i class="fa fa-bullseye"></i><span class="nav-label">Consumers</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/campanhas/configuracoes/acoes/listar"><i class="fa fa-send"></i><span class="nav-label">Ações</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/campanhas/configuracoes/canais/listar"><i class="fa fa-listar-ol"></i><span class="nav-label">Canais</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/campanhas/configuracoes/operadoras/listar"><i class="fa fa-phone"></i><span class="nav-label">Operadoras</span></a>
                            </li>
                            <li>
                                <a href="{{ base_url() }}/campanhas/configuracoes/la/listar"><i class="fa fa-sort-numeric-asc"></i><span class="nav-label">LA</span></a>
                            </li>
                        </ul>
                        <li><a href="{{ base_url() }}/campanhas/listar"><i class="fa fa-plus"></i>listar Campanhas</a></li>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>