<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header" align="center">
                <div class="dropdown profile-element">
                    <span>
                        <img src="{{ base_url() }}/assets/images/logo.png" height="110px"/>
                    </span>
                </div>
                <div class="logo-element" style="background: #f3f3f4;">
                    <img src="{{ base_url() }}/assets/images/logo-2.png" />
                </div>
            </li>
            <li {% if menu_sistema == 'dashboard' %} class="active" {% endif %}>
                <a href="{{ base_url() }}/dashboard"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span></a>
            </li>
            <!-- Menu Configurações do Sistema -->
            {% include 'layout/menus/configuracoes.phtml' %}

            <!-- Menu Interatividade -->
            {% include 'layout/menus/interatividade.phtml' %}

            <!-- Menu Campanhas -->
            {% include 'layout/menus/campanhas.phtml' %}

        </ul>
    </div>
</nav>