<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm welcome-message" style="color:#fff;">Você está logado(a) como: <b>Admin</b></span>
            </li>
            <li>
                <a href="" style="color:#fff;">
                    <i class="fa fa-pencil"></i> Alterar Senha
                </a>
            </li>
            <li>
                <a href="{{ base_url() }}/auth/logout" style="color:#fff;">
                    <i class="fa fa-sign-out"></i> Sair
                </a>
            </li>
        </ul>
    </nav>
</div>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>{{ titulo }}</h2>
        <ol class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                <a href="{{ base_url() }}/">{{ subtitulo }}</a>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>