{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">

        {% for item in messages.error %}
        <div class="alert alert-danger alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            {{item}}
        </div>
        {% endfor %}

            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    <h5>{{subtitulo}}</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" method="POST" action="{{ path_for('editar-oferta', {id: id}) }}">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Nome</label>
                                <div class="col-sm-4">
                                    <input type="text" class="form-control" name="name" required="true" value="{{rows.name}}" placeholder="Digite um nome para a oferta">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Parceiro</label>
                                <div class="col-sm-4">
                                    <select class="form-control select2 form-search" name="partner" id="partner">
                                        <option value="">[Selecione um parceiro]</option>
                                        {% for parceiro in parceiros %}
                                        <option value="{{ parceiro.id }}" {% if rows.partner.id == parceiro.id %} selected="true" {% endif %}>{{ parceiro.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Descrição</label>
                                <div class="col-sm-4">
                                    <textarea id="description" name="description" class="form-control" required="true" style="margin: 0px -4.01563px 0px 0px; height: 70px; width: 499px;" placeholder="Informe a descrição da oferta">{{rows.description}}</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Publico</label>
                                <div class="col-sm-10">
                                    <div><label> <input type="radio" name="public" value="1" {% if rows.public == 1 %} checked="true" required="true" {% endif %}>Sim</label></div>
                                    <div><label> <input type="radio" name="public" value="0" {% if rows.public == 0 %} checked="true" required="true" {% endif %}>Não</label></div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="button" onclick="history.back()">Cancelar</button>
                                    <button class="btn btn-primary" type="submit">Salvar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}