{% extends "layout/layout.phtml" %}

{% block content %}

        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                    {% for perms in sessao.permissions %}
                        {% if perms.name == permissoes.inserir %}
                            <a class="btn btn-success" type="button" href="{{ path_for('inserir-oferta') }}"><i class="fa fa-plus"></i> Adicionar Oferta</a>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <div class="ibox-content">
                        {% for item in messages.success %}
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            {{item}}
                        </div>
                        {% endfor %}

                        <form role="form" class="form-inline" id="filterRows">
                            <div class="form-group">
                                <strong>Filtros:</strong> &nbsp;
                                <select class="form-control select2 form-search" name="name" id="name">
                                    <option value="">[FILTRAR PELO NOME]</option>
                                    {% for oferta in ofertas %}
                                        <option value="{{ oferta.name }}">{{ oferta.name }}</option>
                                    {% endfor %}
                                </select>                                
                            </div>
                            <div class="form-group">
                                <select class="form-control select2 form-search" name="description" id="description">
                                    <option value="">[FILTRAR PELA DESCRIÇÃO]</option>
                                    {% for oferta in ofertas %}
                                        <option value="{{ oferta.description }}">{{ oferta.description }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control select2 form-search" name="partnerId" id="partnerId">
                                    <option value="">[FILTRAR PELO PARCEIRO]</option>
                                    {% for parceiro in parceiros %}
                                    <option value="{{ parceiro.id }}">{{ parceiro.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <select class="form-control select2 form-search" name="public" id="public">
                                    <option value="">[FILTRAR PELA VISIBILIDADE]</option>
                                    <option value="1">Público</option>
                                    <option value="0">Privado</option>
                                </select>
                            </div>
                        </form>

                        <div class="hr-line-dashed"></div>

                        <div class="table-responsive">                       
                            <table id="{{ pagina }}" class="table table-striped table-bordered table-hover">
                                <thead>
                                  <tr>
                                    <th>#</th>
                                    <th>NOME</th>
                                    <th>DESCRIÇÃO</th>
                                    <th>PARCEIRO</th>
                                    <th>VISIBILIDADE</th>                                                                        
                                    <th>AÇÕES</th>                                    
                                  </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>

{% endblock %}